spring:
  datasource:
    url: jdbc:mysql://localhost:3306/week6
    username: root
    password: ss513405^^
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 1000

  sql:
    init:
    mode: never